# Generated by Django 2.1.3 on 2018-11-27 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('auspicio', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('id_evento',),
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id_noticia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('texto', models.CharField(max_length=1500)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
		('tag', models.ManyToManyField(to='main.Tag')),
            ],
            options={
                'ordering': ('id_noticia',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id_tag', models.AutoField(primary_key=True, serialize=False)),
                ('name_tag', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('id_tag',),
            },
        ),

        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
		('tipo', models.CharField(max_length=55)),
                ('estado', models.CharField(max_length=255)),
                ('tag', models.ManyToManyField(to='main.Tag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
		('proyecto', models.ManyToManyField(to='main.Proyecto')),
            ],
            options={
                'ordering': ('user',),
            },
        ),


	migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pro', models.CharField(max_length=255)),
		('tipo', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('id_proyecto',),
            },
        ),




    ]
